### Update comment's sender

PUT http://localhost:3000/comments/673ca4bcfb3be23fb7217852 content-type: application/json

{
"sender": "Robin"
}

### Update comment's content

PUT http://localhost:3000/posts/673ca4bcfb3be23fb7217852 content-type: application/json

{
"content": "Marvel is better then DC"
}

### Delete Comment By ID

DELETE http://localhost:3000/comments/673ca4bcfb3be23fb7217852

### Get Comment By Post ID

GET http://localhost:3000/comments/?postId=673c88b56b1c980fce4558b0

### Get Comment By ID (Does not exist)

GET http://localhost:3000/comments/673ca4bcfb3be23fb7217851

### Get Comment By ID

GET http://localhost:3000/comments/673ca4bcfb3be23fb7217852

### Create Comment

POST http://localhost:3000/comments content-type: application/json

{
	"postId": "673c88b56b1c980fce4558b0",
	"sender": "Batman",
	"content": "We are searching for new recruits to Justice League."
}

### Update post: missing updated post

PUT http://localhost:3000/posts/673c88b56b1c980fce4558b0 content-type: application/json

### Update post missing Id

PUT http://localhost:3000/posts/ content-type: application/json

{
"title": "Justice League Assemble"
}

### Update post's title

PUT http://localhost:3000/posts/673c88b56b1c980fce4558b0 content-type: application/json

{
"title": "Justice League Assemble"
}

### Update post's content

PUT http://localhost:3000/posts/673c88b56b1c980fce4558b0 content-type: application/json

{
"content": "We are searching for new recruits to Justice League, Superpowers are must."
}

### Post id does not exist

PUT http://localhost:3000/posts/6737231dc4d25584d014a6a1 content-type: application/json

{
"content": "Welcome back to me weekly podcast"
}

### Get Post by Id That doesn't exist

GET http://localhost:3000/posts/673c88b56b1c980fce4558b1

### Get Post by Id That exist

GET http://localhost:3000/posts/673c88b56b1c980fce4558b0 

### Add new post

POST http://localhost:3000/posts content-type: application/json

{
    "title": "Justice League", "sender": "Batman", "content": "We are searching for new recruits to Justice League."
}

### Title is required and is not sent to add new post

POST http://localhost:3000/posts content-type: application/json

{
    "sender": "Batman", "content": "We are searching for new recruits to Justice League."
}

### Sender is required and is not sent to add new post

POST http://localhost:3000/posts content-type: application/json

{
    "title": "Justice League", "content": "We are searching for new recruits to Justice League."
}

### Title is required and sent as an empty string to add new post

POST http://localhost:3000/posts content-type: application/json

{
    "title": "", "sender": "Batman", "content": "We are searching for new recruits to Justice League."
}

### Sender is required and sent as an empty string to add new post

POST http://localhost:3000/posts content-type: application/json

{
    "title": "Justice League", "sender": "", "content": "We are searching for new recruits to Justice League."
}

### Content is not required and sent without to add new post

POST http://localhost:3000/posts content-type: application/json

{
    "title": "Justice League", "sender": "Batman"
}

### Get all posts

GET http://localhost:3000/posts

### Get posts by sender

GET http://localhost:3000/posts?sender=Batman